### ISSUE TITLE
Is aiohttp post method implementation correct ?

### ISSUE THREAD

**Issue by sander76** [sander76/aio-powerview-api#6]
..Or any other get,put etc method.

https://github.com/sander76/aio-powerview-api/blob/master/aiopvapi/helpers/aiorequest.py#L40

Wondering whether the implementation is according to "best practices".
Especially I am wondering what to do when the reponse is not what it should be.
I can imagine a 404 should be handled differently compared to a timeout error... Or not ? Should I just return "None" or should I raise any kind of exception which I handle higher up in the call stack ?

**Comment by sander76** [comment]
@etsinko Do you have any opinion on this ?

**Comment by etsinko** [comment]
@sander76 my take on this is to use exceptions. You know what return codes are valid for each of the methods, everything else should raise an exception. 

For example in `put`, you just log an error and return None for `ValueError`, `TimeoutError` and `ClientError`  but what if the user needs to distinguish between a timeout and a wrong request? There is no way to do that now but to parse logs.

The users of these methods (i.e. `Shade`, `Scene` etc) should catch this exceptions if needed and recover, otherwise the exceptions should propagate higher up (i.e. `PowerView` platform in HA)

**Comment by etsinko** [comment]
You could probably create class `AioRequestException` and subclass it as needed, i.e. `AioRequestExceptionWrongStatus` for all status codes that are invalid.

**Comment by sander76** [comment]
@etsinko So an example of recovery from the exceptions would be a retry of the same request in the `shade` or `scene` class ? Or should we implement a retry in the request method itself ?

Regardless of status code (ie 404, 500) I guess there is little point in doing any kind of recovery method after one or more retries have failed ?

So after that some kind of exception should be thrown which will notify the user (in HA for example) ?

**Comment by etsinko** [comment]
Yes, I think `AioRequest` should be lightweight and retry should be done by the user of the method (i.e. `Shade` or `Scene` should retry).

Yes, bad status codes (404, 500) should throw an exception that the users of the `AioRequest` can't process. There is no way `Shade` class can gracefully recover from 404 error which probably means a more serious problem.

So this exception will be propagated up and will be caught by the user of the library (in our case HA)

**Comment by sander76** [comment]
@etsinko Are you sure about where repeating should take place ?
I like the idea of having it at one central location (at `AioRequest`) and the users not having to deal with it...

**Comment by etsinko** [comment]
That would work too. Maybe then add a `num_repeats` parameter to each request and default it to 0.
